const CAPACIDADE_MOCHILA = 53;
const TAMANHO_POPULACAO  = 1000;
const NUMERO_DE_GERACOES = 100;
const NUMERO_REPETE      = 200;
const NUMERO_COMBINA     = 600;
const NUMERO_ALEATORIO   = 200;

module.exports = {
  CAPACIDADE_MOCHILA,
  TAMANHO_POPULACAO,
  NUMERO_DE_GERACOES,
  NUMERO_REPETE,
  NUMERO_COMBINA,
  NUMERO_ALEATORIO
};
